{
 "title": "Autopilot",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(nodename)" } },
   { "name": "health", "label": "Health Check", "query": { "query": "label_values(health)" } },
   { "name": "deviceid", "label": "Device ID", "query": { "query": "label_values(deviceid)" } }
  ]
 },
 "panels": [
  { "title": "Single Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Single Node Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "autopilot_health_checks{node=\"$node\",health=\"$health\",deviceid=\"$deviceid\"}",
     "legendFormat": "{{ health }} for device {{ deviceid }} on {{ node }}"
    }
   ]
  },
  { "title": "All Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PCIe Bandwidths (Gauge)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "autopilot_health_checks{health=\"pciebw\"}",
     "legendFormat": "GPU {{ deviceid }} - {{ node }}"
    }
   ]
  },
  {
   "title": "GPUs with low PCIeBW (less than 4 GB/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopilot_health_checks{health=\"pciebw\"} < 4",
     "legendFormat": "GPU {{deviceid}} - {{node}}"
    }
   ]
  },
  {
   "title": "Secondary NIC by Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{health=\"net-reach\"})by(node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Remapped Rows by Node",
   "type": "gauge",
   "description": "Checks remapped rows on GPUs. If no remapped rows, then value is 0. 1 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{health=\"remapped\"})by(node)",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Timeseries Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Approximate number of new series in this scrape",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(scrape_series_added{job=\"autopilot-metrics-service\"}[1h]) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of samples exposed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(scrape_samples_scraped{job=\"autopilot-metrics-service\"}[1h])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}