global:
  resolve_timeout: 5m
  slack_api_url: >-
    <slack-webhook-api-url>
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
      - alert = slack
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
receivers:
  - name: Autopilot
    slack_configs:
      - channel: <alerts-slack-channel>
        send_resolved: true
        text: |-
          {{ range .Alerts -}}
                  *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
                  *Description:* {{ .Annotations.description }}
                  *Details:*
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
        title: >-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
          | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{
          .CommonLabels.job }}
           Autopilot Health Check Report
  - name: Critical
    slack_configs:
      - channel: <alerts-slack-channel>
        link_names: true
        send_resolved: true
        text: |-
          {{ template "slack.default.text" .}}
          {{ range .Alerts -}}
                  *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
                  *Description:* {{ .Annotations.description }}
                  *Details:*
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
  - name: Default
  - name: 'null'
  - name: Watchdog
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - alertname = InfoInhibitor
      receiver: 'null'
    - receiver: Critical
      matchers:
        - severity = critical
    - receiver: Autopilot
      matchers:
        - alert = autopilot
