global:
  resolve_timeout: 5m
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
receivers:
  - name: Default
  - name: Watchdog
  - name: Critical
  - name: 'null'
  - name: autopilot-pcie
  - name: autopilot-ping
  - name: autopilot-remapped
  - name: autopilot-dcgm
  - name: autopilot-cordon
  - name: autopilot-gpupower
  - name: autopilot-pvc
  - name: autopilot-dcgm3
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - alertname = InfoInhibitor
      receiver: 'null'
    - receiver: autopilot-pcie
      match:
        pcie: autopilot
    - receiver: autopilot-remapped
      match:
        remapped: autopilot
    - receiver: autopilot-dcgm
      match:
        dcgm: autopilot
    - receiver: autopilot-ping
      match:
        ping: autopilot
    - receiver: autopilot-cordon
      match:
        cordon: autopilot
    - receiver: autopilot-gpupower
      match:
        gpupower: autopilot
    - receiver: autopilot-pvc
      match:
        pvc: autopilot
    - receiver: autopilot-dcgm3
      match:
        dcgm3: autopilot
