export NCCL_IB_DISABLE=0
export NCCL_IB_QPS_PER_CONNECTION=8
export NCCL_IB_PCI_RELAXED_ORDERING=1
export NCCL_IB_GID_INDEX=3
export NCCL_ALGO=Ring
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 
export NCCL_IGNORE_CPU_AFFINITY=1
export NCCL_SOCKET_NTHREADS=2
export NCCL_CROSS_NIC=0
export NCCL_BUFFSIZE=67108864
export NCCL_DEBUG=INFO
export NCCL_DMABUF_ENABLE=0
#export NCCL_TOPO_FILE=/var/run/nvidia-topologyd/virtualTopology.xml
#do not set PERTHREAD for RoCE/GDR
#export NCCL_NSOCKS_PERTHREAD=1
#LOC : 0 PIX : 1 PXB : 2 PHB : 3 SYS : 4
