apiVersion: v1
kind: Service
metadata:
  labels:
    app: autopilot
  name: autopilot-metrics-service
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: autopilot
