{{- if .Values.pullSecrets.create -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pullSecrets.imagePullSecretData }}
kind: Secret
metadata:
  name: {{ .Values.pullSecrets.name }}
type: kubernetes.io/dockerconfigjson
{{- end}}