apiVersion: v1
kind: ServiceAccount
metadata:
  name: autopilot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autopilot
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "patch", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["list", "get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autopilot 
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: autopilot 
roleRef: 
  kind: ClusterRole
  name: autopilot 
  apiGroup: rbac.authorization.k8s.io
