{
 "title": "Autopilot Metrics",
 "description": "This dashboard displays Nodes health and utilization",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace!~\"openshift-.*|ibm-.*|nvidia-.*|kube-system|kubeflow|kyverno|mpi-operator|scheduler-plugins|.*grafana.*\"}, namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes with unhealthy GPUs",
   "type": "timeseries",
   "description": "Autopilot labeled nodes with unhealthy GPUs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_node_labels{label_autopilot_ibm_com_gpuhealth=~\".*ERR.*\"} and kube_node_labels{label_autopilot_ibm_com_gpuhealth!~\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU HW Power Brake Slowdown Active",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{node=~\"$node\", health=~\"power-slowdown\"} > 0) by (node, deviceid)"
    }
   ]
  },
  {
   "title": "Idle GPU nodes with GPU Pending Row-Remapping (Sum on a node)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{health=~\"remapped\"}) by (node) > 0 and on (node) count(label_replace(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"\"}==0, \"node\", \"$1\", \"Hostname\", \"(.+)\")) by (node) == 8"
    }
   ]
  },
  {
   "title": "Autopilot Pod Health",
   "type": "timeseries",
   "description": "Checks if any autopilot pods died",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(kube_pod_info and on (pod) (kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\", namespace=~\"autopilot.*\"} > 0 or kube_pod_container_status_terminated_reason{reason=~\"Error\", namespace=~\"autopilot.*\"} > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PING Failures",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(label_replace(autopilot_health_checks{health=\"ping\",node=\"$node\"}, \"targetNode\", \"$1\", \"deviceid\", \"(.*)\"))by(node,targetNode)"
    }
   ]
  },
  {
   "title": "PVC Test",
   "type": "timeseries",
   "description": "Autopilot test to check if a PVC can be created",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum (autopilot_health_checks{health=\"pvc\"}==1) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes with Low PCIe Bandwidth (<3.4 GB/s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(autopilot_health_checks{health=~\"pciebw\"}[12h])) by (node, deviceid) < 3.4 "
    }
   ]
  },
  {
   "title": "GPU Pending Row-Remapping (Sum on a node)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{health=~\"remapped\", node=~\"$node\"}) by (node) > 0"
    }
   ]
  }
 ]
}