apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: autopilot
  name: {{ printf "%s" .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: autopilot
  template:
    metadata:
      annotations:
      {{- toYaml .Values.annotations | nindent 8 }}
      labels:
        app: autopilot
    spec:
      {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | nindent 8 }}
      {{- end}}
      nodeSelector:
      {{- if .Values.nodeSelector }}
      {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end}}
      {{- if .Values.onlyOnGPUNodes }}
        nvidia.com/gpu.present: 'true'
      {{- end}}
      serviceAccountName: autopilot
      {{- if .Values.pullSecrets.create }}
      imagePullSecrets:
      - name: {{ .Values.pullSecrets.name }}
      {{- end}}
      {{- if .Values.onlyOnGPUNodes }}
      initContainers:
        - args:
          - until [ -f /usr/bin/nvidia-smi ]; do echo waiting for nvidia device plug-in to be setup; sleep 5 && exit -1; done
          command:
          - sh
          - -c
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: Always
          name: device-plugin-validation
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000910000
      {{- end}}
      containers:
        - image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          command:
           - sh
           - -c
           - |
             /usr/local/bin/autopilot --port {{ .Values.service.port }} --loglevel={{ .Values.loglevel }} --bw {{ .Values.PCIeBW }} --w {{ .Values.repeat }} --invasive-check-timer {{ .Values.invasive }}
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          name: autopilot
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000910000
            capabilities:
                add:
                - NET_RAW
                - NET_ADMIN
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }} 
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: {{ .Values.service.port }}
              name: healthcheck
            - containerPort: 8081
              name: http
            - containerPort: 8080
              name: readinessprobe
          readinessProbe:
            httpGet:
              path: /readinessprobe
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 120
            timeoutSeconds: 10
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 120
            timeoutSeconds: 15
          {{- if .Values.onlyOnGPUNodes }}
            exec:
              command:
                - nvidia-smi
          {{- else }}
            httpGet:
              path: /readinessprobe
              port: 8080
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.additionalVolumeClaimTemplates }}
        {{- toYaml .Values.additionalVolumeClaimTemplates | nindent 8 }}
        {{- end}}
          
