apiVersion: v1
kind: Service
metadata:
  labels:
    app: autopilot
  name: autopilot-healthchecks
  annotations: 
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: healthcheck
  selector:
    app: autopilot
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: autopilot
  name: autopilot-readinessprobe
spec:
  ports:
    - port: 8080
      protocol: TCP 
      name: readinessprobe
  selector:
    app: autopilot