FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-devel as build

RUN apt -y update && apt -y upgrade && apt -y clean && apt -y autoremove \
        && apt install -y --no-install-recommends build-essential git wget openssh-server && \
        apt -y clean && apt -y autoremove

RUN git clone https://github.com/NVIDIA/cuda-samples.git
WORKDIR cuda-samples/Samples/1_Utilities/bandwidthTest

RUN make SMS="60 70 80 86" 


FROM python:3.9.15-slim

RUN useradd -ms /bin/bash autopilot && usermod -g root autopilot 

WORKDIR /home/autopilot
COPY gpuLocalBandwidthTest.sh /home/autopilot/gpuLocalBandwidthTest.sh
COPY --from=build /workspace/cuda-samples/Samples/1_Utilities/bandwidthTest/bandwidthTest /home/autopilot/bandwidthTest
COPY entrypoint-reduced.py /home/autopilot/entrypoint-reduced.py
COPY briefings.sh /home/autopilot/briefings.sh
RUN python -m pip install --upgrade pip

RUN chmod 755 /home/autopilot/gpuLocalBandwidthTest.sh && chown -hR autopilot /home/autopilot && chmod -R g=u /home/autopilot
# RUN apt -y update && apt -y upgrade && apt install -y vim

CMD python entrypoint-reduced.py