apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cordon-node-alert
  namespace: openshift-monitoring
  labels:
    cordon: autopilot
spec:
  groups:
  - name: autopilot
    rules:
    - alert: CordonAlert
      annotations:
        description: A node has been cordoned - check health of nodes
        summary: Node {{ $labels.node }} has been cordoned
      expr: sum (kube_node_spec_unschedulable) by (node) > 0
      for: 1m
      labels:
        severity: critical
        cordon: autopilot