apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ping-alert
  namespace: openshift-monitoring
  labels:
    ping: autopilot
spec:
  groups:
  - name: ping
    rules:
    - alert: PingAlert
      annotations:
        description: IP {{ $labels.deviceid }} on node {{ $labels.node }} is unreachable
        summary: Node has unreachable IPs
      expr: sum (autopilot_health_checks{health="ping"}==1) by (deviceid)
      for: 1m
      labels:
        severity: critical
        ping: autopilot
        
