name: Test Build Container Image on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'autopilot-daemon/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: autopilot-daemon
          push: false
          tags: test   
